"""add test_column"

Revision ID: 53a75eb8f0ea
Revises: f815051ff1e5
Create Date: 2018-03-04 16:49:55.861999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a75eb8f0ea'
down_revision = 'f815051ff1e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_column', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_test_column'), 'users', ['test_column'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_test_column'), table_name='users')
    op.drop_column('users', 'test_column')
    # ### end Alembic commands ###
