"""initial migration

Revision ID: 6264b694b87e
Revises: 3e15fa5d26a1
Create Date: 2018-03-04 10:11:59.522442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6264b694b87e'
down_revision = '3e15fa5d26a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
