"""gravatar

Revision ID: 656562bbc3d3
Revises: e3bef3e22df4
Create Date: 2018-05-06 17:48:51.050660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656562bbc3d3'
down_revision = 'e3bef3e22df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
